# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: suzuki_kazami.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13suzuki_kazami.proto\x12\rsuzuki_kazami\"\x1c\n\x0cQueueRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\t\"\x1d\n\rQueueResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\t\"Q\n\x08SiteInfo\x12\x0f\n\x07site_id\x18\x01 \x01(\x05\x12\x17\n\x0fsequence_number\x18\x02 \x01(\x05\x12\x1b\n\x13in_critical_section\x18\x03 \x01(\x08\"\x87\x01\n\x13RequestTokenMessage\x12\x0f\n\x07site_id\x18\x01 \x01(\t\x12\x17\n\x0fsequence_number\x18\x02 \x01(\x05\x12\x1b\n\x13in_critical_section\x18\x03 \x01(\x08\x12\x11\n\thas_token\x18\x04 \x01(\x08\x12\x16\n\x0eserver_address\x18\x05 \x01(\t\"\x85\x01\n\x11ReplyTokenMessage\x12\x0f\n\x07site_id\x18\x01 \x01(\t\x12\x17\n\x0fsequence_number\x18\x02 \x01(\x05\x12\x1b\n\x13in_critical_section\x18\x03 \x01(\x08\x12\x11\n\thas_token\x18\x04 \x01(\x08\x12\x16\n\x0eserver_address\x18\x05 \x01(\t2\xfb\x03\n\x0cSuzukiKazami\x12\x45\n\x08GetQueue\x12\x1b.suzuki_kazami.QueueRequest\x1a\x1c.suzuki_kazami.QueueResponse\x12I\n\x0bUpdateQueue\x12\x1c.suzuki_kazami.QueueResponse\x1a\x1c.suzuki_kazami.QueueResponse\x12I\n\x0b\x44\x65leteQueue\x12\x1c.suzuki_kazami.QueueResponse\x1a\x1c.suzuki_kazami.QueueResponse\x12T\n\x0cRequestToken\x12\".suzuki_kazami.RequestTokenMessage\x1a .suzuki_kazami.ReplyTokenMessage\x12Z\n\x14\x45nterCriticalSection\x12 .suzuki_kazami.ReplyTokenMessage\x1a .suzuki_kazami.ReplyTokenMessage\x12\\\n\x16ReleaseCriticalSection\x12 .suzuki_kazami.ReplyTokenMessage\x1a .suzuki_kazami.ReplyTokenMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'suzuki_kazami_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_QUEUEREQUEST']._serialized_start=38
  _globals['_QUEUEREQUEST']._serialized_end=66
  _globals['_QUEUERESPONSE']._serialized_start=68
  _globals['_QUEUERESPONSE']._serialized_end=97
  _globals['_SITEINFO']._serialized_start=99
  _globals['_SITEINFO']._serialized_end=180
  _globals['_REQUESTTOKENMESSAGE']._serialized_start=183
  _globals['_REQUESTTOKENMESSAGE']._serialized_end=318
  _globals['_REPLYTOKENMESSAGE']._serialized_start=321
  _globals['_REPLYTOKENMESSAGE']._serialized_end=454
  _globals['_SUZUKIKAZAMI']._serialized_start=457
  _globals['_SUZUKIKAZAMI']._serialized_end=964
# @@protoc_insertion_point(module_scope)
