# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import suzuki_kazami_pb2 as suzuki__kazami__pb2


class SuzukiKazamiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetQueue = channel.unary_unary(
                '/suzuki_kazami.SuzukiKazami/GetQueue',
                request_serializer=suzuki__kazami__pb2.QueueRequest.SerializeToString,
                response_deserializer=suzuki__kazami__pb2.QueueResponse.FromString,
                )
        self.UpdateQueue = channel.unary_unary(
                '/suzuki_kazami.SuzukiKazami/UpdateQueue',
                request_serializer=suzuki__kazami__pb2.QueueResponse.SerializeToString,
                response_deserializer=suzuki__kazami__pb2.QueueResponse.FromString,
                )
        self.DeleteQueue = channel.unary_unary(
                '/suzuki_kazami.SuzukiKazami/DeleteQueue',
                request_serializer=suzuki__kazami__pb2.QueueResponse.SerializeToString,
                response_deserializer=suzuki__kazami__pb2.QueueResponse.FromString,
                )
        self.RequestToken = channel.unary_unary(
                '/suzuki_kazami.SuzukiKazami/RequestToken',
                request_serializer=suzuki__kazami__pb2.RequestTokenMessage.SerializeToString,
                response_deserializer=suzuki__kazami__pb2.ReplyTokenMessage.FromString,
                )
        self.EnterCriticalSection = channel.unary_unary(
                '/suzuki_kazami.SuzukiKazami/EnterCriticalSection',
                request_serializer=suzuki__kazami__pb2.ReplyTokenMessage.SerializeToString,
                response_deserializer=suzuki__kazami__pb2.ReplyTokenMessage.FromString,
                )
        self.ReleaseCriticalSection = channel.unary_unary(
                '/suzuki_kazami.SuzukiKazami/ReleaseCriticalSection',
                request_serializer=suzuki__kazami__pb2.ReplyTokenMessage.SerializeToString,
                response_deserializer=suzuki__kazami__pb2.ReplyTokenMessage.FromString,
                )


class SuzukiKazamiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnterCriticalSection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseCriticalSection(self, request, context):
        """rpc RecieveToken(ReplyTokenMessage) returns (ReplyTokenMessage);
        rpc SendToken(ReplyTokenMessage) returns (ReplyTokenMessage);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SuzukiKazamiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQueue,
                    request_deserializer=suzuki__kazami__pb2.QueueRequest.FromString,
                    response_serializer=suzuki__kazami__pb2.QueueResponse.SerializeToString,
            ),
            'UpdateQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateQueue,
                    request_deserializer=suzuki__kazami__pb2.QueueResponse.FromString,
                    response_serializer=suzuki__kazami__pb2.QueueResponse.SerializeToString,
            ),
            'DeleteQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteQueue,
                    request_deserializer=suzuki__kazami__pb2.QueueResponse.FromString,
                    response_serializer=suzuki__kazami__pb2.QueueResponse.SerializeToString,
            ),
            'RequestToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestToken,
                    request_deserializer=suzuki__kazami__pb2.RequestTokenMessage.FromString,
                    response_serializer=suzuki__kazami__pb2.ReplyTokenMessage.SerializeToString,
            ),
            'EnterCriticalSection': grpc.unary_unary_rpc_method_handler(
                    servicer.EnterCriticalSection,
                    request_deserializer=suzuki__kazami__pb2.ReplyTokenMessage.FromString,
                    response_serializer=suzuki__kazami__pb2.ReplyTokenMessage.SerializeToString,
            ),
            'ReleaseCriticalSection': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseCriticalSection,
                    request_deserializer=suzuki__kazami__pb2.ReplyTokenMessage.FromString,
                    response_serializer=suzuki__kazami__pb2.ReplyTokenMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'suzuki_kazami.SuzukiKazami', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SuzukiKazami(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/suzuki_kazami.SuzukiKazami/GetQueue',
            suzuki__kazami__pb2.QueueRequest.SerializeToString,
            suzuki__kazami__pb2.QueueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/suzuki_kazami.SuzukiKazami/UpdateQueue',
            suzuki__kazami__pb2.QueueResponse.SerializeToString,
            suzuki__kazami__pb2.QueueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/suzuki_kazami.SuzukiKazami/DeleteQueue',
            suzuki__kazami__pb2.QueueResponse.SerializeToString,
            suzuki__kazami__pb2.QueueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/suzuki_kazami.SuzukiKazami/RequestToken',
            suzuki__kazami__pb2.RequestTokenMessage.SerializeToString,
            suzuki__kazami__pb2.ReplyTokenMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EnterCriticalSection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/suzuki_kazami.SuzukiKazami/EnterCriticalSection',
            suzuki__kazami__pb2.ReplyTokenMessage.SerializeToString,
            suzuki__kazami__pb2.ReplyTokenMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReleaseCriticalSection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/suzuki_kazami.SuzukiKazami/ReleaseCriticalSection',
            suzuki__kazami__pb2.ReplyTokenMessage.SerializeToString,
            suzuki__kazami__pb2.ReplyTokenMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
